[common]
# 填写你服务器的公网 IP
server_addr = 42.4.63.133
# 填写服务端 frps.ini 中配置的 bind_port
server_port = 7000
# 如果服务端设置了 token，这里必须一致
token = guo3194589716

# 定义一个代理，名字自定义，例如 "web_local"
[web_local]
type = tcp
# 本地服务地址
local_ip = 127.0.0.1
# 本地服务端口
local_port = 1234
remote_port = 1234
# (可选) 自定义子域名，如果没配置域名可忽略此项，直接通过 IP+端口访问
# custom_domains = myapp.example.com 