"""add_rating_to_food_records

Revision ID: 96898b889cb6
Revises: 0ad998d2c721
Create Date: 2026-06-05 23:11:25.982458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96898b889cb6'
down_revision: Union[str, None] = '0ad998d2c721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_records', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_records', 'rating')
    # ### end Alembic commands ###
